// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/resources/sortarray.proto

package protocols;

public final class SortArrayProtocol {
  private SortArrayProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SortArrayOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocols.SortArray)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 size = 1;</code>
     */
    boolean hasSize();
    /**
     * <code>required int32 size = 1;</code>
     */
    int getSize();

    /**
     * <code>repeated int32 arr = 2;</code>
     */
    java.util.List<java.lang.Integer> getArrList();
    /**
     * <code>repeated int32 arr = 2;</code>
     */
    int getArrCount();
    /**
     * <code>repeated int32 arr = 2;</code>
     */
    int getArr(int index);
  }
  /**
   * Protobuf type {@code protocols.SortArray}
   */
  public  static final class SortArray extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocols.SortArray)
      SortArrayOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SortArray.newBuilder() to construct.
    private SortArray(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SortArray() {
      size_ = 0;
      arr_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SortArray(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              size_ = input.readInt32();
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                arr_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              arr_.add(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                arr_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                arr_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          arr_ = java.util.Collections.unmodifiableList(arr_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocols.SortArrayProtocol.internal_static_protocols_SortArray_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocols.SortArrayProtocol.internal_static_protocols_SortArray_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocols.SortArrayProtocol.SortArray.class, protocols.SortArrayProtocol.SortArray.Builder.class);
    }

    private int bitField0_;
    public static final int SIZE_FIELD_NUMBER = 1;
    private int size_;
    /**
     * <code>required int32 size = 1;</code>
     */
    public boolean hasSize() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 size = 1;</code>
     */
    public int getSize() {
      return size_;
    }

    public static final int ARR_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> arr_;
    /**
     * <code>repeated int32 arr = 2;</code>
     */
    public java.util.List<java.lang.Integer>
        getArrList() {
      return arr_;
    }
    /**
     * <code>repeated int32 arr = 2;</code>
     */
    public int getArrCount() {
      return arr_.size();
    }
    /**
     * <code>repeated int32 arr = 2;</code>
     */
    public int getArr(int index) {
      return arr_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, size_);
      }
      for (int i = 0; i < arr_.size(); i++) {
        output.writeInt32(2, arr_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, size_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < arr_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(arr_.get(i));
        }
        size += dataSize;
        size += 1 * getArrList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocols.SortArrayProtocol.SortArray)) {
        return super.equals(obj);
      }
      protocols.SortArrayProtocol.SortArray other = (protocols.SortArrayProtocol.SortArray) obj;

      boolean result = true;
      result = result && (hasSize() == other.hasSize());
      if (hasSize()) {
        result = result && (getSize()
            == other.getSize());
      }
      result = result && getArrList()
          .equals(other.getArrList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSize()) {
        hash = (37 * hash) + SIZE_FIELD_NUMBER;
        hash = (53 * hash) + getSize();
      }
      if (getArrCount() > 0) {
        hash = (37 * hash) + ARR_FIELD_NUMBER;
        hash = (53 * hash) + getArrList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocols.SortArrayProtocol.SortArray parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocols.SortArrayProtocol.SortArray parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocols.SortArrayProtocol.SortArray parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocols.SortArrayProtocol.SortArray parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocols.SortArrayProtocol.SortArray parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocols.SortArrayProtocol.SortArray parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocols.SortArrayProtocol.SortArray parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocols.SortArrayProtocol.SortArray parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocols.SortArrayProtocol.SortArray parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocols.SortArrayProtocol.SortArray parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocols.SortArrayProtocol.SortArray parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocols.SortArrayProtocol.SortArray parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocols.SortArrayProtocol.SortArray prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocols.SortArray}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocols.SortArray)
        protocols.SortArrayProtocol.SortArrayOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocols.SortArrayProtocol.internal_static_protocols_SortArray_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocols.SortArrayProtocol.internal_static_protocols_SortArray_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocols.SortArrayProtocol.SortArray.class, protocols.SortArrayProtocol.SortArray.Builder.class);
      }

      // Construct using protocols.SortArrayProtocol.SortArray.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        size_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        arr_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocols.SortArrayProtocol.internal_static_protocols_SortArray_descriptor;
      }

      @java.lang.Override
      public protocols.SortArrayProtocol.SortArray getDefaultInstanceForType() {
        return protocols.SortArrayProtocol.SortArray.getDefaultInstance();
      }

      @java.lang.Override
      public protocols.SortArrayProtocol.SortArray build() {
        protocols.SortArrayProtocol.SortArray result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protocols.SortArrayProtocol.SortArray buildPartial() {
        protocols.SortArrayProtocol.SortArray result = new protocols.SortArrayProtocol.SortArray(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.size_ = size_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          arr_ = java.util.Collections.unmodifiableList(arr_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.arr_ = arr_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocols.SortArrayProtocol.SortArray) {
          return mergeFrom((protocols.SortArrayProtocol.SortArray)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocols.SortArrayProtocol.SortArray other) {
        if (other == protocols.SortArrayProtocol.SortArray.getDefaultInstance()) return this;
        if (other.hasSize()) {
          setSize(other.getSize());
        }
        if (!other.arr_.isEmpty()) {
          if (arr_.isEmpty()) {
            arr_ = other.arr_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureArrIsMutable();
            arr_.addAll(other.arr_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasSize()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocols.SortArrayProtocol.SortArray parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocols.SortArrayProtocol.SortArray) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int size_ ;
      /**
       * <code>required int32 size = 1;</code>
       */
      public boolean hasSize() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 size = 1;</code>
       */
      public int getSize() {
        return size_;
      }
      /**
       * <code>required int32 size = 1;</code>
       */
      public Builder setSize(int value) {
        bitField0_ |= 0x00000001;
        size_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 size = 1;</code>
       */
      public Builder clearSize() {
        bitField0_ = (bitField0_ & ~0x00000001);
        size_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> arr_ = java.util.Collections.emptyList();
      private void ensureArrIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          arr_ = new java.util.ArrayList<java.lang.Integer>(arr_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int32 arr = 2;</code>
       */
      public java.util.List<java.lang.Integer>
          getArrList() {
        return java.util.Collections.unmodifiableList(arr_);
      }
      /**
       * <code>repeated int32 arr = 2;</code>
       */
      public int getArrCount() {
        return arr_.size();
      }
      /**
       * <code>repeated int32 arr = 2;</code>
       */
      public int getArr(int index) {
        return arr_.get(index);
      }
      /**
       * <code>repeated int32 arr = 2;</code>
       */
      public Builder setArr(
          int index, int value) {
        ensureArrIsMutable();
        arr_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 arr = 2;</code>
       */
      public Builder addArr(int value) {
        ensureArrIsMutable();
        arr_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 arr = 2;</code>
       */
      public Builder addAllArr(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureArrIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, arr_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 arr = 2;</code>
       */
      public Builder clearArr() {
        arr_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocols.SortArray)
    }

    // @@protoc_insertion_point(class_scope:protocols.SortArray)
    private static final protocols.SortArrayProtocol.SortArray DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocols.SortArrayProtocol.SortArray();
    }

    public static protocols.SortArrayProtocol.SortArray getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SortArray>
        PARSER = new com.google.protobuf.AbstractParser<SortArray>() {
      @java.lang.Override
      public SortArray parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SortArray(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SortArray> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SortArray> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protocols.SortArrayProtocol.SortArray getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocols_SortArray_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocols_SortArray_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036main/resources/sortarray.proto\022\tprotoc" +
      "ols\"&\n\tSortArray\022\014\n\004size\030\001 \002(\005\022\013\n\003arr\030\002 " +
      "\003(\005B\036\n\tprotocolsB\021SortArrayProtocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protocols_SortArray_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocols_SortArray_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocols_SortArray_descriptor,
        new java.lang.String[] { "Size", "Arr", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
